services:
  web:
    build: .
    volumes:
      - DataVolume1:/shared
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  DataVolume1:
      driver: local



# docker volume create --name DataVolume1
# docker run -ti --name=Container1 -v DataVolume1:/datavolume1 ubuntu